'use client'
// Copyright 2026 Yogvid Wankhede and the Vishwakarma project authors
// SPDX-License-Identifier: Apache-2.0

import { type CssOptions, type TokenSet, toCss } from '@vishwakarma/tokens'
import { type ReactNode, useMemo } from 'react'

/**
 * Serialise a token set into the document at runtime.
 *
 * This is the exception, not the route. Tokens should be compiled to CSS at build time,
 * where the cost is paid once and the browser can cache, compress, and preload the result.
 * Emitting them per response costs bytes on every document, delays first paint by the size
 * of the sheet, and — because the sheet is inline — cannot be cached separately from the
 * HTML.
 *
 * It earns its place in exactly one situation: when the token set is not known until the
 * request is served. Multi-tenant products that paint each customer's brand, editors that
 * preview a palette live, and white-labelled embeds all choose their tokens after the
 * build has finished, and for them the alternative is a build per tenant.
 *
 * Render it in the head, above anything that consumes the variables. If it lands below the
 * first component that uses them, that component paints once unstyled.
 */
export interface TokenStylesProps {
  /** The token set to serialise. */
  set: TokenSet
  /**
   * Transform options. Defaults match the rest of this package: theme overrides scoped by
   * `[data-theme]`, which is the only strategy that a three-state preference can drive.
   */
  options?: CssOptions
  /** CSP nonce, required when `style-src` does not allow inline styles. */
  nonce?: string
}

/**
 * A `</style>` sequence inside the sheet would terminate the element early and let the
 * remainder be parsed as markup. Token values are authored data, not attacker input, in
 * most deployments — but "most" is doing too much work in a multi-tenant renderer, which
 * is precisely the case this component exists for. Escaping the closing bracket costs
 * nothing and closes the hole.
 */
function escapeStyleText(css: string): string {
  return css.replace(/<\/(style)/gi, '<\\/$1')
}

export function TokenStyles({ set, options, nonce }: TokenStylesProps): ReactNode {
  const css = useMemo(
    () => escapeStyleText(toCss(set, options ?? { themeStrategy: 'attribute' })),
    [set, options],
  )

  return (
    // biome-ignore lint/security/noDangerouslySetInnerHtml: a stylesheet has to be text; the content is generated by the token transform and escaped above.
    <style {...(nonce ? { nonce } : {})} dangerouslySetInnerHTML={{ __html: css }} />
  )
}
