'use client'
// Copyright 2026 Yogvid Wankhede and the Vishwakarma project authors
// SPDX-License-Identifier: Apache-2.0

import { useSyncExternalStore } from 'react'
import type { ResolvedTheme } from './settings.js'

/**
 * Reading the operating system's preferences.
 *
 * All of these use `useSyncExternalStore` rather than the far more common `useState` plus
 * `useEffect` pair. The difference is not stylistic. With an effect, the first client
 * render always reports the fallback and only corrects after commit, so a user whose OS is
 * dark gets one rendered frame of light interface on every mount of every component that
 * asks. `useSyncExternalStore` reads the live value during render, so the first frame is
 * already right, and it is the only API that gives React a coherent story for what to do
 * during hydration when the two sides genuinely cannot agree.
 */

const DARK_QUERY = '(prefers-color-scheme: dark)'
const FORCED_COLORS_QUERY = '(forced-colors: active)'

function subscribeToQuery(query: string): (callback: () => void) => () => void {
  return (callback) => {
    if (typeof window === 'undefined' || !window.matchMedia) return () => {}
    const list = window.matchMedia(query)
    list.addEventListener('change', callback)
    return () => list.removeEventListener('change', callback)
  }
}

/**
 * A media query as a boolean.
 *
 * The snapshot must be a primitive. Returning a `MediaQueryList` or any freshly allocated
 * object here would make React see a new value on every render and loop forever, which is
 * the classic way this hook is got wrong.
 */
export function useMediaQuery(query: string, serverFallback = false): boolean {
  return useSyncExternalStore(
    subscribeToQuery(query),
    () => {
      if (typeof window === 'undefined' || !window.matchMedia) return serverFallback
      return window.matchMedia(query).matches
    },
    () => serverFallback,
  )
}

/**
 * The operating system's colour-scheme preference.
 *
 * The server snapshot is `light`. The server cannot know the answer — `prefers-color-scheme`
 * is not sent with the request, and nothing in an HTTP header carries it — so a value must
 * be invented, and the invented value should match whatever the stylesheet paints by
 * default. Token CSS generated by `@vishwakarma/tokens` declares `color-scheme: light` at
 * `:root`, so `light` is the choice that keeps the server snapshot and the server-rendered
 * pixels telling the same story.
 *
 * This does not cause a flash for a user on a dark OS, because it is not what puts the
 * theme on the document: the pre-paint script does that, before React has run at all.
 * By the time this hook corrects itself during hydration, the page is already dark.
 */
export function useSystemTheme(): ResolvedTheme {
  return useMediaQuery(DARK_QUERY, false) ? 'dark' : 'light'
}

/**
 * Whether the platform is forcing its own colour palette.
 *
 * In forced-colours mode — Windows High Contrast and its equivalents — the user agent
 * overrides author colours with a small system palette chosen by the user, usually because
 * they cannot read the one you picked. The right response is not to fight it. It is to
 * stop drawing the things that silently vanish under it: borders expressed as background
 * colour, focus rings drawn with `box-shadow`, state conveyed by fill alone, and icons
 * that are really coloured rectangles. All of those become invisible, and the component
 * that looked most polished in normal mode is usually the one that disappears.
 *
 * The server fallback is `false`, because assuming forced colours and stripping decoration
 * for everyone would be a worse default than the reverse.
 */
export function useForcedColors(): boolean {
  return useMediaQuery(FORCED_COLORS_QUERY, false)
}

/**
 * Whether the user has asked for more contrast without forcing a palette.
 *
 * Distinct from forced colours: here you keep control of the palette and are expected to
 * use it better — stronger borders, higher text contrast, less reliance on subtle tonal
 * separation between surfaces.
 */
export function usePrefersMoreContrast(): boolean {
  return useMediaQuery('(prefers-contrast: more)', false)
}
