#!/usr/bin/env python3
"""
Generate a typed TypeScript client and React hook from a probe report.

The types come from the payload probe_api.py actually observed, not from the
provider's documentation, because documentation drifts and the response does
not. The generated client returns a domain type you own, so no provider-shaped
field reaches a component and swapping providers later touches one file.

When the probe says `server-side-only` the browser cannot call the endpoint —
either CORS is absent or a key is involved — so a route handler is emitted and
the client points at that instead of at the third party.

Usage
  scaffold_client.py --report probe-report.json --out ./src
  scaffold_client.py --report probe-report.json --out ./src --dry-run
  scaffold_client.py --report probe-report.json --out ./src --force

Exit codes
  0  files written (or, with --dry-run, would be written)
  1  refused: a target exists and --force was not given
  2  bad or unusable report

Copyright 2026 Yogvid Wankhede and the Vishwakarma project authors
SPDX-License-Identifier: Apache-2.0
"""

import argparse
import json
import os
import re
import sys

RESERVED = {"default", "function", "class", "interface", "return", "new", "delete"}


def pascal(s):
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", s) if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) or "Resource"


def camel(s):
    p = pascal(s)
    return p[:1].lower() + p[1:]


def prop_key(k):
    """Quote any key that is not a plain identifier, so the emitted TS parses."""
    return k if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", k) and k not in RESERVED else f'"{k}"'


def ts_type(node, name, interfaces, depth=0):
    """
    Render a schema node as a TS type, hoisting nested objects into named
    interfaces so the result is readable rather than one deep inline literal.
    """
    t = node.get("type")
    if t == "string":
        return "string"
    if t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        items = node.get("items", {})
        if items.get("type") == "unknown":
            return "unknown[]"
        inner = ts_type(items, name + "Item", interfaces, depth + 1)
        # A heterogeneous sample means T[] would be a lie.
        return f"{inner}[]" if node.get("homogeneous", True) else "unknown[]"
    if t == "object":
        iface = pascal(name)
        lines = []
        for k, v in node.get("properties", {}).items():
            child = ts_type(v, f"{name}-{k}", interfaces, depth + 1)
            optional = "?" if v.get("nullable") else ""
            fmt = v.get("format")
            if fmt == "date-time":
                lines.append(f"  /** ISO 8601 in the observed payload. */")
            elif fmt == "uri":
                lines.append(f"  /** URL in the observed payload. */")
            lines.append(f"  {prop_key(k)}{optional}: {child}")
        if node.get("truncated"):
            lines.append("  // Probe sampled the first 40 keys; more may exist.")
        body = "\n".join(lines) or "  [key: string]: unknown"
        interfaces[iface] = f"export interface {iface} {{\n{body}\n}}"
        return iface
    return "unknown"


CLIENT = '''// Generated by Vishwakarma scaffold_client.py from a live probe of:
//   {url}
// Probed {status} in {lat}ms, {bytes} bytes. Verdict: {verdict}.
// Types describe the payload as observed, not as documented. Re-probe and
// regenerate if the provider changes shape.

{interfaces}
{root_decl}

export class {root}Error extends Error {{
  constructor(
    message: string,
    readonly status?: number,
    readonly retryable = false,
  ) {{
    super(message)
    this.name = '{root}Error'
  }}
}}

const ENDPOINT = {endpoint}
const TIMEOUT_MS = 5_000
const MAX_ATTEMPTS = 3

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

/**
 * Retry only what retrying can fix. A 404 or a 401 will answer the same way
 * every time, so repeating it just multiplies latency before the same failure.
 */
function retryable(status: number): boolean {{
  return status === 429 || status >= 500
}}

export async function fetch{root}(init?: RequestInit): Promise<{root}> {{
  let lastError: unknown

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {{
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS)

    try {{
      const response = await fetch(ENDPOINT, {{
        ...init,
        signal: controller.signal,
        headers: {{ Accept: 'application/json', ...init?.headers }},
      }})

      if (!response.ok) {{
        const canRetry = retryable(response.status)
        if (canRetry && attempt < MAX_ATTEMPTS) {{
          // Honour Retry-After when the server sends one; it knows better than we do.
          const after = Number(response.headers.get('retry-after'))
          const backoff = Number.isFinite(after) && after > 0
            ? after * 1000
            : 2 ** attempt * 100 + Math.random() * 100
          await sleep(backoff)
          continue
        }}
        throw new {root}Error(
          `{name} responded ${{response.status}}`,
          response.status,
          canRetry,
        )
      }}

      return (await response.json()) as {root}
    }} catch (error) {{
      lastError = error
      if (error instanceof {root}Error) throw error
      // An abort is a timeout here, and a timeout is worth one more try.
      if (attempt < MAX_ATTEMPTS) {{
        await sleep(2 ** attempt * 100 + Math.random() * 100)
        continue
      }}
    }} finally {{
      clearTimeout(timer)
    }}
  }}

  throw new {root}Error(
    `{name} unreachable after ${{MAX_ATTEMPTS}} attempts: ${{String(lastError)}}`,
    undefined,
    true,
  )
}}
'''

HOOK = '''// Generated by Vishwakarma scaffold_client.py.
'use client'

import {{ useCallback, useEffect, useRef, useState }} from 'react'
import {{ fetch{root}, {root}Error, type {root} }} from '{import_path}'

/**
 * Every state a caller must render. `isEmpty` is separate from `data === null`
 * because a successful response carrying nothing is a different screen from a
 * request that has not resolved, and collapsing them produces a spinner that
 * never stops.
 */
export interface Use{root}Result {{
  data: {root} | null
  error: {root}Error | null
  isLoading: boolean
  isEmpty: boolean
  refetch: () => void
}}

function isEmptyPayload(value: {root} | null): boolean {{
  if (value === null) return true
  if (Array.isArray(value)) return value.length === 0
  if (typeof value === 'object') return Object.keys(value).length === 0
  return false
}}

export function use{root}(): Use{root}Result {{
  const [data, setData] = useState<{root} | null>(null)
  const [error, setError] = useState<{root}Error | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [nonce, setNonce] = useState(0)
  // Guards against setting state after unmount, and against an earlier slow
  // response overwriting a later fast one.
  const current = useRef(0)

  useEffect(() => {{
    const run = ++current.current
    setIsLoading(true)
    setError(null)

    fetch{root}()
      .then((result) => {{
        if (current.current !== run) return
        setData(result)
      }})
      .catch((cause) => {{
        if (current.current !== run) return
        setError(
          cause instanceof {root}Error
            ? cause
            : new {root}Error(String(cause)),
        )
      }})
      .finally(() => {{
        if (current.current !== run) return
        setIsLoading(false)
      }})

    return () => {{
      current.current++
    }}
  }}, [nonce])

  const refetch = useCallback(() => setNonce((n) => n + 1), [])

  return {{ data, error, isLoading, isEmpty: !isLoading && isEmptyPayload(data), refetch }}
}}
'''

ROUTE = '''// Generated by Vishwakarma scaffold_client.py.
// The probe found no usable Access-Control-Allow-Origin{key_clause}, so the
// browser cannot call this endpoint directly. This handler keeps the call —
// and any credential — on the server.

import {{ NextResponse }} from 'next/server'

const UPSTREAM = '{url}'

export async function GET() {{
  try {{
    const response = await fetch(UPSTREAM, {{
      headers: {{
        Accept: 'application/json',{auth_header}
      }},
      // Cache briefly so a burst of readers costs the provider one call.
      next: {{ revalidate: 60 }},
    }})

    if (!response.ok) {{
      return NextResponse.json(
        {{ error: '{name} upstream error' }},
        {{ status: response.status === 429 ? 429 : 502 }},
      )
    }}

    return NextResponse.json(await response.json())
  }} catch {{
    return NextResponse.json({{ error: '{name} unreachable' }}, {{ status: 504 }})
  }}
}}
'''


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    p.add_argument("--report", required=True)
    p.add_argument("--out", default="./src", help="source root to write into")
    p.add_argument("--env-key", help="env var name holding the API key")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--force", action="store_true", help="overwrite existing files")
    args = p.parse_args()

    try:
        with open(args.report) as f:
            r = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(json.dumps({"error": f"cannot read report: {e}"}))
        print(f"error: {e}", file=sys.stderr)
        return 2

    if not r.get("ok") or not r.get("schema"):
        print(json.dumps({"error": "report is not ok - probe the endpoint successfully first"}))
        print(f"error: probe verdict was '{r.get('verdict')}' - nothing to scaffold",
              file=sys.stderr)
        return 2

    name = r["name"]
    root = pascal(name)
    server_only = r["verdict"] == "server-side-only"

    interfaces = {}
    root_src = ts_type(r["schema"], name, interfaces)

    # ts_type names a root object interface after the skill, so emitting an alias
    # as well would declare the same identifier twice. Alias only when the root is
    # an array or a primitive, where there is no interface to collide with.
    iface_block = "\n\n".join(interfaces.values())
    if root_src == root:
        root_decl = ""
    else:
        root_decl = (
            "\n/** What this module promises callers. "
            "Rename fields here, not at call sites. */\n"
            f"export type {root} = {root_src}\n"
        )

    route_path = f"/api/{re.sub(r'[^a-z0-9-]+', '-', name.lower()).strip('-')}"
    endpoint = f"'{route_path}'" if server_only else f"'{r['url']}'"

    client = CLIENT.format(
        url=r["url"], status=r["status"], lat=r["latency_ms"]["max"],
        bytes=r["bytes"], verdict=r["verdict"], interfaces=iface_block,
        root=root, root_decl=root_decl, name=name, endpoint=endpoint,
    )
    hook = HOOK.format(root=root, import_path=f"@/lib/api/{name}")

    planned = {
        os.path.join(args.out, "lib", "api", f"{name}.ts"): client,
        os.path.join(args.out, "hooks", f"use{root}.ts"): hook,
    }

    if server_only:
        auth = ""
        key_clause = ""
        if args.env_key:
            auth = f"\n        Authorization: `Bearer ${{process.env.{args.env_key}}}`,"
            key_clause = " and a key is required"
        planned[os.path.join(args.out, "app", "api",
                             route_path.split("/")[-1], "route.ts")] = ROUTE.format(
            url=r["url"], name=name, auth_header=auth, key_clause=key_clause)

    existing = [p for p in planned if os.path.exists(p)]
    if existing and not args.force and not args.dry_run:
        print(json.dumps({"error": "targets exist", "paths": existing}))
        print("refusing to overwrite:", file=sys.stderr)
        for e in existing:
            print(f"  {e}", file=sys.stderr)
        print("re-run with --force, or --dry-run to see the output first", file=sys.stderr)
        return 1

    written = []
    for path, contents in planned.items():
        if args.dry_run:
            written.append(path)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(contents)
        written.append(path)

    env_line = None
    if args.env_key:
        env_line = f"{args.env_key}="
        env_path = os.path.join(os.path.dirname(args.out.rstrip("/")) or ".", ".env.example")
        if not args.dry_run:
            prior = ""
            if os.path.exists(env_path):
                with open(env_path) as f:
                    prior = f.read()
            if args.env_key not in prior:
                with open(env_path, "a") as f:
                    f.write(("" if prior.endswith("\n") or not prior else "\n") + env_line + "\n")
                written.append(env_path)

    out = {
        "name": name, "root_type": root, "verdict": r["verdict"],
        "server_side_only": server_only, "dry_run": args.dry_run,
        "written": written, "env_entry": env_line,
        "interfaces": sorted(interfaces),
    }
    print(json.dumps(out, indent=2))

    verb = "would write" if args.dry_run else "wrote"
    print(f"\n{verb} {len(written)} file(s) for '{name}' ({root}):", file=sys.stderr)
    for w in written:
        print(f"  {w}", file=sys.stderr)
    if server_only:
        print(f"\n  Probe said server-side-only, so calls go through {route_path}",
              file=sys.stderr)
        if not args.env_key:
            print("  No --env-key given: add the credential to the route handler yourself.",
                  file=sys.stderr)
    print(f"\n  Import:  import {{ use{root} }} from '@/hooks/use{root}'", file=sys.stderr)
    print("  Render loading, error, and empty before shipping - all three are in the hook.",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
