/**
 * The skill catalog.
 *
 * Generated by scripts/generate-catalog.mjs — do not edit by hand. Add a skill file to
 * this directory and re-run the generator.
 */

import type { SkillManifest } from '../manifest.js'

export { colourSystems } from './colour-systems.js'
export { designJudgment } from './design-judgment.js'
export { layoutComposition } from './layout-composition.js'
export { typographicSystems } from './typographic-systems.js'

import { colourSystems } from './colour-systems.js'
import { designJudgment } from './design-judgment.js'
import { layoutComposition } from './layout-composition.js'
import { typographicSystems } from './typographic-systems.js'

/** Every skill in the catalog, in stable order. */
export const catalog: SkillManifest[] = [
  colourSystems,
  designJudgment,
  layoutComposition,
  typographicSystems,
]

/** Look up a skill by its id. */
export const catalogById = new Map<string, SkillManifest>(
  catalog.map((skill) => [skill.id, skill]),
)

/** Every category present in the catalog. */
export const categories = Array.from(new Set(catalog.map((skill) => skill.category))).sort()

/** Skills in a given category. */
export function skillsInCategory(category: SkillManifest['category']): SkillManifest[] {
  return catalog.filter((skill) => skill.category === category)
}

/**
 * Resolve a skill selection to a closed set, pulling in every dependency.
 *
 * A skill that declares `requires` is useless without its dependencies, so installing
 * it alone would produce guidance referencing rules the agent has never seen. This
 * walks the graph so a selection is always internally complete.
 */
export function resolveSelection(ids: string[]): SkillManifest[] {
  const selected = new Map<string, SkillManifest>()
  const queue = [...ids]

  while (queue.length > 0) {
    const id = queue.shift() as string
    if (selected.has(id)) continue
    const skill = catalogById.get(id)
    if (!skill) throw new Error(`Unknown skill "${id}". Run \`vishwakarma list\` to see the catalog.`)
    selected.set(id, skill)
    for (const required of skill.activation.requires ?? []) queue.push(required)
  }

  return catalog.filter((skill) => selected.has(skill.id))
}
