/**
 * The skill catalog.
 *
 * Generated by scripts/generate-catalog.mjs — do not edit by hand. Add a skill file to
 * this directory and re-run the generator.
 */

import type { SkillManifest } from '../manifest.js'

export { accessibleComponents } from './accessible-components.js'
export { colourSystems } from './colour-systems.js'
export { componentArchitecture } from './component-architecture.js'
export { designJudgment } from './design-judgment.js'
export { designTokens } from './design-tokens.js'
export { informationArchitecture } from './information-architecture.js'
export { interactionDesign } from './interaction-design.js'
export { interfaceCopy } from './interface-copy.js'
export { layoutComposition } from './layout-composition.js'
export { microInteractions } from './micro-interactions.js'
export { motionDesign } from './motion-design.js'
export { renderingPerformance } from './rendering-performance.js'
export { responsiveArchitecture } from './responsive-architecture.js'
export { scrollExperiences } from './scroll-experiences.js'
export { surfaceAndDepth } from './surface-and-depth.js'
export { themingSystems } from './theming-systems.js'
export { typographicSystems } from './typographic-systems.js'

import { accessibleComponents } from './accessible-components.js'
import { colourSystems } from './colour-systems.js'
import { componentArchitecture } from './component-architecture.js'
import { designJudgment } from './design-judgment.js'
import { designTokens } from './design-tokens.js'
import { informationArchitecture } from './information-architecture.js'
import { interactionDesign } from './interaction-design.js'
import { interfaceCopy } from './interface-copy.js'
import { layoutComposition } from './layout-composition.js'
import { microInteractions } from './micro-interactions.js'
import { motionDesign } from './motion-design.js'
import { renderingPerformance } from './rendering-performance.js'
import { responsiveArchitecture } from './responsive-architecture.js'
import { scrollExperiences } from './scroll-experiences.js'
import { surfaceAndDepth } from './surface-and-depth.js'
import { themingSystems } from './theming-systems.js'
import { typographicSystems } from './typographic-systems.js'

/** Every skill in the catalog, in stable order. */
export const catalog: SkillManifest[] = [
  accessibleComponents,
  colourSystems,
  componentArchitecture,
  designJudgment,
  designTokens,
  informationArchitecture,
  interactionDesign,
  interfaceCopy,
  layoutComposition,
  microInteractions,
  motionDesign,
  renderingPerformance,
  responsiveArchitecture,
  scrollExperiences,
  surfaceAndDepth,
  themingSystems,
  typographicSystems,
]

/** Look up a skill by its id. */
export const catalogById = new Map<string, SkillManifest>(
  catalog.map((skill) => [skill.id, skill]),
)

/** Every category present in the catalog. */
export const categories = Array.from(new Set(catalog.map((skill) => skill.category))).sort()

/** Skills in a given category. */
export function skillsInCategory(category: SkillManifest['category']): SkillManifest[] {
  return catalog.filter((skill) => skill.category === category)
}

/**
 * Resolve a skill selection to a closed set, pulling in every dependency.
 *
 * A skill that declares `requires` is useless without its dependencies, so installing
 * it alone would produce guidance referencing rules the agent has never seen. This
 * walks the graph so a selection is always internally complete.
 */
export function resolveSelection(ids: string[]): SkillManifest[] {
  const selected = new Map<string, SkillManifest>()
  const queue = [...ids]

  while (queue.length > 0) {
    const id = queue.shift() as string
    if (selected.has(id)) continue
    const skill = catalogById.get(id)
    if (!skill) throw new Error(`Unknown skill "${id}". Run \`vishwakarma list\` to see the catalog.`)
    selected.set(id, skill)
    for (const required of skill.activation.requires ?? []) queue.push(required)
  }

  return catalog.filter((skill) => selected.has(skill.id))
}
