#!/usr/bin/env node
// Copyright 2026 Yogvid Wankhede and the Vishwakarma project authors
// SPDX-License-Identifier: Apache-2.0

/**
 * Regenerates the skill catalog barrel from whatever is on disk.
 *
 * The catalog grows one file at a time, and a hand-maintained barrel is exactly the sort
 * of file people forget to update — producing a skill that exists, compiles, is tested,
 * and is never loaded by anything. Deriving the barrel from the directory removes that
 * failure mode entirely.
 *
 * Run: node scripts/generate-catalog.mjs
 */

import { readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CATALOG = join(ROOT, 'packages/skills/src/catalog')

/** Find the exported manifest constant in a skill file. */
const EXPORT_PATTERN = /export\s+const\s+([A-Za-z_$][\w$]*)\s*:\s*SkillManifest\b/

async function main() {
  const entries = await readdir(CATALOG, { withFileTypes: true })

  const skillFiles = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => name.endsWith('.ts') && name !== 'index.ts' && !name.endsWith('.test.ts'))
    .sort()

  const found = []
  const problems = []

  for (const file of skillFiles) {
    const source = await readFile(join(CATALOG, file), 'utf8')
    const match = EXPORT_PATTERN.exec(source)
    if (!match) {
      problems.push(`${file}: no "export const <name>: SkillManifest" declaration found`)
      continue
    }
    found.push({ file: file.replace(/\.ts$/, ''), exportName: match[1] })
  }

  const lines = [
    '/**',
    ' * The skill catalog.',
    ' *',
    ' * Generated by scripts/generate-catalog.mjs — do not edit by hand. Add a skill file to',
    ' * this directory and re-run the generator.',
    ' */',
    '',
    "import type { SkillManifest } from '../manifest.js'",
    '',
  ]

  for (const { file, exportName } of found) {
    lines.push(`export { ${exportName} } from './${file}.js'`)
  }

  lines.push('')
  for (const { file, exportName } of found) {
    lines.push(`import { ${exportName} } from './${file}.js'`)
  }

  lines.push('')
  lines.push('/** Every skill in the catalog, in stable order. */')
  lines.push('export const catalog: SkillManifest[] = [')
  for (const { exportName } of found) lines.push(`  ${exportName},`)
  lines.push(']')
  lines.push('')
  lines.push('/** Look up a skill by its id. */')
  lines.push('export const catalogById = new Map<string, SkillManifest>(')
  lines.push('  catalog.map((skill) => [skill.id, skill]),')
  lines.push(')')
  lines.push('')
  lines.push('/** Every category present in the catalog. */')
  lines.push('export const categories = Array.from(new Set(catalog.map((skill) => skill.category))).sort()')
  lines.push('')
  lines.push('/** Skills in a given category. */')
  lines.push('export function skillsInCategory(category: SkillManifest[\'category\']): SkillManifest[] {')
  lines.push('  return catalog.filter((skill) => skill.category === category)')
  lines.push('}')
  lines.push('')
  lines.push('/**')
  lines.push(' * Resolve a skill selection to a closed set, pulling in every dependency.')
  lines.push(' *')
  lines.push(' * A skill that declares `requires` is useless without its dependencies, so installing')
  lines.push(' * it alone would produce guidance referencing rules the agent has never seen. This')
  lines.push(' * walks the graph so a selection is always internally complete.')
  lines.push(' */')
  lines.push('export function resolveSelection(ids: string[]): SkillManifest[] {')
  lines.push('  const selected = new Map<string, SkillManifest>()')
  lines.push('  const queue = [...ids]')
  lines.push('')
  lines.push('  while (queue.length > 0) {')
  lines.push('    const id = queue.shift() as string')
  lines.push('    if (selected.has(id)) continue')
  lines.push('    const skill = catalogById.get(id)')
  lines.push('    if (!skill) throw new Error(`Unknown skill "${id}". Run \\`vishwakarma list\\` to see the catalog.`)')
  lines.push('    selected.set(id, skill)')
  lines.push('    for (const required of skill.activation.requires ?? []) queue.push(required)')
  lines.push('  }')
  lines.push('')
  lines.push('  return catalog.filter((skill) => selected.has(skill.id))')
  lines.push('}')
  lines.push('')

  await writeFile(join(CATALOG, 'index.ts'), lines.join('\n'), 'utf8')

  process.stdout.write(`Catalog barrel regenerated with ${found.length} skill(s).\n`)
  for (const problem of problems) process.stderr.write(`  warning: ${problem}\n`)
}

main().catch((error) => {
  process.stderr.write(`${error?.stack ?? error}\n`)
  process.exit(1)
})
